name: project_fetp_form
description: A web app for the Iraqi FETP Program.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  cloud_firestore: ^3.1.5
  connectivity_plus: ^2.2.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  provider: ^6.0.2
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  internet_connection_checker: ^0.0.1+3
  rxdart: ^0.27.3
  mailer: ^5.0.2


  # cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: noto_arabic
  #     fonts:
  #       - asset: assets/fonts/noto_arabic.ttf
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #   - family: CustomIcons
  #     fonts:
  #     - asset: assets/fonts/CustomIcons.ttf
